* sigscheme/configure.in   - Change package name to 'SigScheme' (and keep tarname 'sigscheme')   - Add dist-bzip2 option to AM_INIT_AUTOMAKE   - Replace AC_CONFIG_HEADER with more preferable AC_CONFIG_HEADERS   - Add check for md5 commands * sigscheme/Makefile.am   - (DISTCLEANFILES):     * New variable     * Add gnuify-changelog.pl   - (DIST_SUM_LIST): New variable   - (ChangeLog): Place gnuify-changelog.pl to builddir   - (distcheck-hook, distclean-local):     * New target     * Add ChangeLog handling for distcheck   - (sum): New target

diff --git a/sigscheme/Makefile.am b/sigscheme/Makefile.am
--- a/sigscheme/Makefile.am
+++ b/sigscheme/Makefile.am
@@ -1,20 +1,27 @@
 SUBDIRS = doc m4 tools src lib test test-c bench
-EXTRA_DIST = \
-        TODO autogen.sh \
-        compare-scm.sh runbench.sh runtest.sh runtest-tail-rec.sh
 
 UIM_REPOSITORY = http://anonsvn.freedesktop.org/svn/uim
 SSCM_REPOSITORY = $(UIM_REPOSITORY)/branches/r5rs/sigscheme
 TAGS_REPOSITORY = $(UIM_REPOSITORY)/tags
+DIST_SUM_LIST = $(PACKAGE)-$(VERSION).md5
 
-.PHONY: FORCE
+EXTRA_DIST = \
+        TODO autogen.sh \
+        compare-scm.sh runbench.sh runtest.sh runtest-tail-rec.sh
+
+DISTCLEANFILES = tools/gnuify-changelog.pl $(DIST_SUM_LIST)
+
+.PHONY: FORCE sum
 FORCE:
 
 ChangeLog: FORCE
 	svn export $(UIM_REPOSITORY)/trunk/tools/gnuify-changelog.pl \
-	    $(top_srcdir)/tools/gnuify-changelog.pl
-	svn log | $(top_srcdir)/tools/gnuify-changelog.pl > $@
+	    tools/gnuify-changelog.pl
+	svn log | tools/gnuify-changelog.pl > $@
 	@test -s $@ && echo 'ChangeLog updated successfully.'
+
+sum: FORCE
+	$(MD5) $(DIST_ARCHIVES) >$(DIST_SUM_LIST)
 
 # To generate ChangeLog for a release properly, a source tree for official
 # release must not be obtained by 'svn export' but 'svn co'.
@@ -24,8 +31,20 @@ ChangeLog: FORCE
 # svn co $(TAGS_REPOSITORY)/sigscheme-x.y.z
 # cd sigscheme-x.y.z
 # ./configure
-# make dist
+# make distcheck sum
 dist-hook:
-	svn info \
-	    | $(EGREP) -q "^Repository Root: .+/svn/uim/tags/sigscheme-" \
-	    || (echo "error: not an official release. checkout tagged one"; test)
+	svn info | $(EGREP) -q "^Repository Root: .+/svn/uim/tags/sigscheme-" \
+	    || (echo "error: not an official release. checkout tagged one"; exit 1)
+
+# for 'svn log'
+distcheck-hook:
+	cp -Rp $(top_srcdir)/.svn $(distdir)/_build
+	touch $(distdir)/_build/.svn/prepared-for-distcheck
+
+distclean-local:
+	if test '$(top_srcdir)' != '$(top_builddir)'; then  \
+	    rm -f ChangeLog;                                    \
+	fi
+	if test -f .svn/prepared-for-distcheck; then    \
+	    rm -rf .svn;                                \
+	fi
